image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Default build cache settings to extend from
.build_cached:
  cache:
    key: "gradle-build"
    paths:
      # Only cache the gradle directory, as we do not use a shared cache
      - .gradle/
    policy: pull

build-order-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: build
  script:
    gradle order-microservice:assemble order-microservice:testClasses

checkStyle-order-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle order-microservice:checkstyleMain order-microservice:checkStyleTest
  allow_failure: true


PMD-order-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle order-microservice:pmdMain
  allow_failure: true

pitest-order-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: test
  script:
    - |
      gradle order-microservice:pitest &&
      MUTATION_SCORE=$(grep -oP "(?<=<th>Mutation Score</th><td>)([0-9]+)" order-microservice/build/reports/pitest/index.html) &&
      if [[ $MUTATION_SCORE -ge 70 ]]; then
        echo "Mutation score is greater than or equal to 70%."
      else
        echo "Mutation score is less than 70%."
        exit 1
      fi
  allow_failure: true

#test-order-microservice:
#  extends:
#    - .build_cached
#  needs:
#    - gradle_build
#    - pitest-order-microservice
#  dependencies:
#    - gradle_build
#    - pitest-order-microservice
#  stage: test
#  script:
#    - gradle order-microservice:test order-microservice:jacocoTestReport --stacktrace
#    - cat order-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
#  coverage: /([0-9]{1,3})%/

#mutation-score-check:
#  extends:
#    - .build_cached
#  needs:
#    - pitest-order-microservice
#  dependencies:
#    - pitest-order-microservice
#  stage: test
#  script:
#    - ls order-microservice/build
